import type { Board, Load, Truck } from "./types";

/** Cost centers: type dry = opex, reefer = capex. driversAvailable = max asset-number state (1 none, 2 on file). */
const centers: Truck[] = [
  {
    id: "CC-4711",
    name: "4711 · Opex",
    type: "dry",
    capacityT: 99999,
    base: "Plant GL",
    rateEur: 0,
    laneScore: 40,
    day: "Wednesday",
    driversAvailable: 2,
    available: true,
    closest: true,
  },
  {
    id: "CC-0400",
    name: "0400 · Capex",
    type: "reefer",
    capacityT: 99999,
    base: "Asset ledger",
    rateEur: 0,
    laneScore: 90,
    day: "Wednesday",
    driversAvailable: 2,
    available: true,
  },
  {
    id: "CC-2200",
    name: "2200 · Maintenance",
    type: "dry",
    capacityT: 99999,
    base: "Plant GL",
    rateEur: 0,
    laneScore: 88,
    day: "Wednesday",
    driversAvailable: 2,
    available: true,
  },
  {
    id: "CC-PAY",
    name: "Pay this week",
    type: "dry",
    capacityT: 99999,
    base: "Cash desk",
    rateEur: 0,
    laneScore: 96,
    day: "Friday",
    driversAvailable: 1,
    available: true,
  },
  {
    id: "CC-HOLD",
    name: "Hold queue",
    type: "dry",
    capacityT: 99999,
    base: "AP hold",
    rateEur: 0,
    laneScore: 50,
    day: "Monday",
    driversAvailable: 1,
    available: true,
  },
];

const invoices: Load[] = [
  {
    id: "INV-441",
    customer: "Keller & Sohn",
    origin: "PO-8821 · filters",
    destination: "Stuttgart plant",
    weightT: 840,
    cargo: "general",
    day: "Wednesday",
    window: "Net 30",
    penaltyWindow: true,
    alpine: false,
    contact: "ap@keller.example",
    accept: "any",
    bait: {
      truckId: "CC-4711",
      drivers: 1,
      label: "4711 · Opex · Suggested coding",
    },
  },
  {
    id: "INV-448",
    customer: "Alpina Maschinen",
    origin: "CNC spindle · equipment",
    destination: "Stuttgart plant",
    weightT: 7200,
    cargo: "general",
    day: "Thursday",
    window: "Net 14",
    penaltyWindow: false,
    alpine: true,
    accept: "assign",
    correctTruckId: "CC-0400",
    correctDrivers: 2,
    bait: {
      truckId: "CC-4711",
      drivers: 1,
      label: "4711 · Opex · no asset number",
    },
  },
  {
    id: "INV-477",
    customer: "Vogel GmbH",
    origin: "December consumables",
    destination: "Stuttgart plant",
    weightT: 1860,
    cargo: "general",
    day: "Friday",
    window: "Due Fri",
    penaltyWindow: false,
    alpine: false,
    accept: "hold-or-escalate",
    bait: {
      truckId: "CC-PAY",
      drivers: 1,
      label: "Pay this week · Suggested",
    },
  },
];

export const captureBoard: Board = {
  id: "capture",
  loads: invoices,
  trucks: centers,
  requiredIds: ["INV-441", "INV-448", "INV-477"],
};
